model_args:
  model_name: "vit"
  input_vars: {
    "pressure_levels": [
               't_1000','t_850','t_700','t_500','t_200',
               'z_1000','z_850','z_700','z_500','z_200',
               'u_1000','u_850','u_700','u_500','u_200',
               'v_1000','v_850','v_700','v_500','v_200',
               'q_1000','q_850','q_700','q_500','q_200'
               ],
    "single_level": [
               't2m','msl','stl1','sst','siconc','sd','tprate',
               ],
  }
  input_cons: ['lsm', 'slt', 'z']
  output_vars: ['t2m','t_850','z_500','q_700','tp']
  ##########
  patch_size: 4
  hidden_size: 384
  num_layers: 8
  num_heads: 12
  mlp_dim: 768
  #########
  learning_rate: 1e-3
  t_max: 500
  patience: 20
  max_epochs: 300

data_args:
  data_dir: "/root/Weather_Data/flood_season_data"
  center: "cmcc"
  crop_size: [180, 360]
  batch_size: 24
  num_workers: 0
  input_vars: {
    "pressure_levels": [
               't_1000','t_850','t_700','t_500','t_200',
               'z_1000','z_850','z_700','z_500','z_200',
               'u_1000','u_850','u_700','u_500','u_200',
               'v_1000','v_850','v_700','v_500','v_200',
               'q_1000','q_850','q_700','q_500','q_200'
               ],
    "single_level": [
               't2m','msl','stl1','sst','siconc','sd','tprate',
               ],
  }
  input_cons: ['lsm', 'slt', 'z']
  output_vars: ['t2m','t_850','z_500','q_700','tp']
  ens_count: 10
  nwp_subfolder: "processed_data_10ens"